//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarly_Web_book
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScholarlyWebBook_AppDBEntities : DbContext
    {
        public ScholarlyWebBook_AppDBEntities()
            : base("name=ScholarlyWebBook_AppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_PDF_ANSWERS> TBL_PDF_ANSWERS { get; set; }
        public virtual DbSet<TBL_PDF_QUESTION_TAGS> TBL_PDF_QUESTION_TAGS { get; set; }
        public virtual DbSet<TBL_COMMENTS> TBL_COMMENTS { get; set; }
        public virtual DbSet<TBL_Groups> TBL_Groups { get; set; }
        public virtual DbSet<TBL_Groups_Emails> TBL_Groups_Emails { get; set; }
        public virtual DbSet<TBL_ANNOTATION_RATINGS> TBL_ANNOTATION_RATINGS { get; set; }
        public virtual DbSet<TBL_USER_SPECIALIZATION> TBL_USER_SPECIALIZATION { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
        public virtual DbSet<TBL_PDF_UPLOADS> TBL_PDF_UPLOADS { get; set; }
    }
}
