//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarly_Web_book
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PDF_UPLOADS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PDF_UPLOADS()
        {
            this.TBL_PDF_QUESTION_TAGS = new HashSet<TBL_PDF_QUESTION_TAGS>();
        }
    
        public int PDF_UPLOADED_ID { get; set; }
        public string USER_ID { get; set; }
        public string PDF_SAVED_PATH { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string PUB_MED_ID { get; set; }
        public string ARTICLE { get; set; }
        public string AUTHOR { get; set; }
        public string DOI_NUMBER { get; set; }
        public string HTML_CONTENT { get; set; }
        public Nullable<bool> IS_PUBLIC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PDF_QUESTION_TAGS> TBL_PDF_QUESTION_TAGS { get; set; }
    }
}
