//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarly_Web_book
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PDF_QUESTION_TAGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PDF_QUESTION_TAGS()
        {
            this.TBL_PDF_ANSWERS = new HashSet<TBL_PDF_ANSWERS>();
        }
    
        public int QUESTION_ID { get; set; }
        public string QUESTION { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string USER_ID { get; set; }
        public Nullable<int> PDF_UPLOADED_ID { get; set; }
        public Nullable<int> IsPublic { get; set; }
        public string Notes { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PDF_ANSWERS> TBL_PDF_ANSWERS { get; set; }
        public virtual TBL_PDF_UPLOADS TBL_PDF_UPLOADS { get; set; }
    }
}
