//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarly_Web_book
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ANNOTATION_RATINGS
    {
        public int RATING_ID { get; set; }
        public Nullable<bool> IS_LIKED { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> QUESTION_ID { get; set; }
        public Nullable<int> ANSWER_ID { get; set; }
    }
}
