//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholarly_Web_book
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Users
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string University { get; set; }
        public string Specialisation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        public Nullable<int> Specialization_Id { get; set; }
        public string Current_position { get; set; }
        public string Current_Location { get; set; }
        public Nullable<bool> Gender { get; set; }
        public int UserID { get; set; }
    
        public virtual TBL_USER_SPECIALIZATION TBL_USER_SPECIALIZATION { get; set; }
    }
}
